using System.Globalization;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Mailcoded.Protocol.TypeScript;

/// <summary>The TypeScript view of the wire contract, derived from what ProtocolJsonContext registers.
/// A pure function of the assembly: the same input always yields the same bytes.</summary>
internal static class TypeScriptEmitter
{
    private const string Namespace = "Mailcoded.Protocol";
    private const int CommentWidth = 96;

    private static readonly HashSet<Type> Numbers =
    [
        typeof(byte), typeof(sbyte), typeof(short), typeof(ushort), typeof(int), typeof(uint),
        typeof(long), typeof(ulong), typeof(float), typeof(double), typeof(decimal),
    ];

    public static string Emit(Assembly protocol, XmlDocs docs)
    {
        ArgumentNullException.ThrowIfNull(protocol);
        ArgumentNullException.ThrowIfNull(docs);

        var context = Required(protocol, "ProtocolJsonContext");
        var records = CollectRecords(context);
        var inbound = InboundReachable(records);

        var output = new StringBuilder();
        output.Append("// GENERATED by tools/Mailcoded.Protocol.TypeScript from Mailcoded.Protocol. Do not edit.\n");
        output.Append("// Regenerate with `npm run gen:types` (or scripts/gen-types.sh). The drift test in\n");
        output.Append("// tests/Mailcoded.Core.Tests/Protocol/TypeScriptTypesTests.cs fails while this file is stale.\n");
        output.Append("/* eslint-disable */\n\n");

        var version = Required(protocol, "ProtocolConstants").GetField("Version")!.GetRawConstantValue();
        output.Append("export const PROTOCOL_VERSION = ").Append(Literal(version)).Append(";\n\n");

        foreach (var type in records.OrderBy(t => t.Name, StringComparer.Ordinal))
            EmitInterface(output, type, records, inbound.Contains(type), docs);

        foreach (var type in ConstantClasses(protocol))
            EmitConstants(output, type, docs);

        foreach (var type in protocol.GetTypes().Where(t => t.IsEnum && t.Namespace == Namespace).OrderBy(t => t.Name, StringComparer.Ordinal))
            EmitEnum(output, type, docs);

        EmitMethodMap(output, protocol, records);
        EmitNotificationMap(output, protocol, records);

        return output.ToString();
    }

    public static string FirstDifference(string current, string generated)
    {
        var a = current.Split('\n');
        var b = generated.Split('\n');

        for (var i = 0; i < Math.Max(a.Length, b.Length); i++)
        {
            var left = i < a.Length ? a[i] : "<end of file>";
            var right = i < b.Length ? b[i] : "<end of file>";
            if (left != right) return $"First difference at line {i + 1}: checked in `{left}`, generated `{right}`.";
        }

        return "Files differ only in length.";
    }

    private static HashSet<Type> CollectRecords(Type context)
    {
        var records = new HashSet<Type>();
        var queue = new Queue<Type>();

        // The registered type is only reachable as constructor data; the attribute exposes no property for it.
        foreach (var attribute in context.GetCustomAttributesData())
        {
            if (attribute.AttributeType != typeof(JsonSerializableAttribute)) continue;
            if (attribute.ConstructorArguments[0].Value is Type registered && IsRecord(registered)) queue.Enqueue(registered);
        }

        while (queue.TryDequeue(out var type))
        {
            if (!records.Add(type)) continue;

            foreach (var property in WireProperties(type))
                foreach (var referenced in ReferencedTypes(property.PropertyType))
                    if (IsRecord(referenced)) queue.Enqueue(referenced);
        }

        return records;
    }

    /// <summary>Types a client may send. Their defaulted members are optional on the wire because
    /// the daemon fills them in; everything else is always written by the daemon.</summary>
    private static HashSet<Type> InboundReachable(HashSet<Type> records)
    {
        var inbound = new HashSet<Type>();
        var queue = new Queue<Type>(records.Where(t =>
            t.Name.EndsWith("Params", StringComparison.Ordinal) || t.Name is "JsonRpcRequest" or "JsonRpcNotification"));

        while (queue.TryDequeue(out var type))
        {
            if (!inbound.Add(type)) continue;

            foreach (var property in WireProperties(type))
                foreach (var referenced in ReferencedTypes(property.PropertyType))
                    if (records.Contains(referenced)) queue.Enqueue(referenced);
        }

        return inbound;
    }

    private static void EmitInterface(StringBuilder output, Type type, HashSet<Type> records, bool inbound, XmlDocs docs)
    {
        Comment(output, docs.ForType(type), indent: "");

        var properties = WireProperties(type).ToList();
        if (properties.Count == 0)
        {
            output.Append("export interface ").Append(type.Name).Append(" {}\n\n");
            return;
        }

        output.Append("export interface ").Append(type.Name).Append(" {\n");

        var nullability = new NullabilityInfoContext();

        foreach (var property in properties)
        {
            Comment(output, docs.ForProperty(property), indent: "  ");

            var info = nullability.Create(property);
            var optional = !IsRequired(property) && (IsNullable(property, info) || inbound);

            output.Append("  ").Append(WireName(property)).Append(optional ? "?: " : ": ")
                .Append(TsType(property.PropertyType, info, records)).Append(";\n");
        }

        output.Append("}\n\n");
    }

    private static void EmitConstants(StringBuilder output, Type type, XmlDocs docs)
    {
        var fields = ConstantFields(type);

        Comment(output, docs.ForType(type), indent: "");
        output.Append("export const ").Append(type.Name).Append(" = {\n");

        foreach (var field in fields)
        {
            Comment(output, docs.ForField(field), indent: "  ");
            output.Append("  ").Append(field.Name).Append(": ").Append(Literal(field.GetRawConstantValue())).Append(",\n");
        }

        output.Append("} as const;\n");

        if (fields.All(f => f.FieldType == typeof(string)))
        {
            output.Append("export type ").Append(type.Name).Append("Value = (typeof ").Append(type.Name)
                .Append(")[keyof typeof ").Append(type.Name).Append("];\n");
        }

        output.Append('\n');
    }

    private static void EmitEnum(StringBuilder output, Type type, XmlDocs docs)
    {
        Comment(output, docs.ForType(type), indent: "");
        output.Append("export const ").Append(type.Name).Append(" = {\n");

        foreach (var field in type.GetFields(BindingFlags.Public | BindingFlags.Static).OrderBy(f => f.MetadataToken))
        {
            Comment(output, docs.ForField(field), indent: "  ");
            output.Append("  ").Append(field.Name).Append(": ")
                .Append(Literal(Convert.ChangeType(field.GetRawConstantValue(), Enum.GetUnderlyingType(type), CultureInfo.InvariantCulture)))
                .Append(",\n");
        }

        output.Append("} as const;\n");
        output.Append("export type ").Append(type.Name).Append(" = (typeof ").Append(type.Name)
            .Append(")[keyof typeof ").Append(type.Name).Append("];\n\n");
    }

    /// <summary>Pairs every method name with its Params and Result records by the naming convention
    /// the protocol follows; a method without its pair is a generation failure, not a gap.</summary>
    private static void EmitMethodMap(StringBuilder output, Assembly protocol, HashSet<Type> records)
    {
        output.Append("export interface RpcMethodMap {\n");

        foreach (var field in ConstantFields(Required(protocol, "RpcMethods")))
        {
            var parameters = Pair(protocol, records, field.Name + "Params", field);
            var result = Pair(protocol, records, field.Name + "Result", field);

            output.Append("  ").Append(Quote((string)field.GetRawConstantValue()!))
                .Append(": { params: ").Append(parameters.Name).Append("; result: ").Append(result.Name).Append(" };\n");
        }

        output.Append("}\n");
        output.Append("export type RpcMethodName = keyof RpcMethodMap;\n\n");
    }

    private static void EmitNotificationMap(StringBuilder output, Assembly protocol, HashSet<Type> records)
    {
        output.Append("export interface RpcNotificationMap {\n");

        foreach (var field in ConstantFields(Required(protocol, "RpcNotifications")))
        {
            var payload = Pair(protocol, records, field.Name + "Notification", field);
            output.Append("  ").Append(Quote((string)field.GetRawConstantValue()!)).Append(": ").Append(payload.Name).Append(";\n");
        }

        output.Append("}\n");
        output.Append("export type RpcNotificationName = keyof RpcNotificationMap;\n");
    }

    private static Type Pair(Assembly protocol, HashSet<Type> records, string name, FieldInfo method)
    {
        var type = protocol.GetType(Namespace + "." + name);

        if (type is null || !records.Contains(type))
        {
            throw new InvalidOperationException(
                $"'{method.GetRawConstantValue()}' has no registered {name}. Every method needs its Params and Result "
                + "records on ProtocolJsonContext, and every notification its Notification record.");
        }

        return type;
    }

    private static string TsType(Type type, NullabilityInfo? info, HashSet<Type> records)
    {
        var underlying = Nullable.GetUnderlyingType(type) ?? type;

        if (underlying == typeof(string)) return "string";
        if (underlying == typeof(bool)) return "boolean";
        if (Numbers.Contains(underlying)) return "number";
        if (underlying == typeof(JsonElement)) return "unknown";

        if (underlying.IsArray)
            return "readonly " + TsType(underlying.GetElementType()!, info?.ElementType, records) + "[]";

        if (underlying.IsGenericType)
        {
            var definition = underlying.GetGenericTypeDefinition();
            var arguments = underlying.GetGenericArguments();

            if (arguments.Length == 1 && IsSequence(definition))
                return "readonly " + TsType(arguments[0], info?.GenericTypeArguments.ElementAtOrDefault(0), records) + "[]";

            if (arguments.Length == 2 && IsMap(definition) && arguments[0] == typeof(string))
                return "Readonly<Record<string, " + TsType(arguments[1], info?.GenericTypeArguments.ElementAtOrDefault(1), records) + ">>";
        }

        if (records.Contains(underlying)) return underlying.Name;

        throw new NotSupportedException($"No TypeScript mapping for {type}. Add one to TypeScriptEmitter.TsType.");
    }

    private static IEnumerable<Type> ReferencedTypes(Type type)
    {
        var underlying = Nullable.GetUnderlyingType(type) ?? type;

        if (underlying.IsArray)
        {
            foreach (var t in ReferencedTypes(underlying.GetElementType()!)) yield return t;
            yield break;
        }

        if (underlying.IsGenericType)
        {
            foreach (var argument in underlying.GetGenericArguments())
                foreach (var t in ReferencedTypes(argument)) yield return t;
            yield break;
        }

        yield return underlying;
    }

    private static bool IsSequence(Type definition) =>
        definition == typeof(IReadOnlyList<>) || definition == typeof(IReadOnlyCollection<>)
        || definition == typeof(IEnumerable<>) || definition == typeof(IList<>)
        || definition == typeof(ICollection<>) || definition == typeof(List<>);

    private static bool IsMap(Type definition) =>
        definition == typeof(IReadOnlyDictionary<,>) || definition == typeof(IDictionary<,>) || definition == typeof(Dictionary<,>);

    private static bool IsRecord(Type type) =>
        type.Namespace == Namespace && type.IsClass && !type.IsAbstract && !type.IsGenericType && !type.IsEnum;

    private static IEnumerable<Type> ConstantClasses(Assembly protocol) =>
        protocol.GetTypes()
            .Where(t => t.Namespace == Namespace && t.IsClass && t.IsAbstract && t.IsSealed && ConstantFields(t).Count > 0)
            .OrderBy(t => t.Name, StringComparer.Ordinal);

    private static List<FieldInfo> ConstantFields(Type type) =>
        type.GetFields(BindingFlags.Public | BindingFlags.Static)
            .Where(f => f.IsLiteral && !f.IsInitOnly)
            .OrderBy(f => f.MetadataToken)
            .ToList();

    private static IEnumerable<PropertyInfo> WireProperties(Type type) =>
        type.GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .Where(p => p.GetMethod is not null && p.GetIndexParameters().Length == 0 && p.GetCustomAttribute<JsonIgnoreAttribute>() is null)
            .OrderBy(p => p.MetadataToken);

    private static string WireName(PropertyInfo property) =>
        property.GetCustomAttribute<JsonPropertyNameAttribute>()?.Name ?? JsonNamingPolicy.CamelCase.ConvertName(property.Name);

    private static bool IsRequired(PropertyInfo property) => property.GetCustomAttribute<RequiredMemberAttribute>() is not null;

    private static bool IsNullable(PropertyInfo property, NullabilityInfo info) =>
        Nullable.GetUnderlyingType(property.PropertyType) is not null
        || info.ReadState == NullabilityState.Nullable
        || info.WriteState == NullabilityState.Nullable;

    private static Type Required(Assembly protocol, string name) =>
        protocol.GetType(Namespace + "." + name)
        ?? throw new InvalidOperationException($"{Namespace}.{name} is missing from the protocol assembly.");

    private static string Literal(object? value) => value switch
    {
        string text => Quote(text),
        bool flag => flag ? "true" : "false",
        IFormattable number => number.ToString(null, CultureInfo.InvariantCulture),
        null => "null",
        _ => throw new NotSupportedException($"No literal form for {value.GetType()}."),
    };

    private static string Quote(string text)
    {
        var builder = new StringBuilder(text.Length + 2).Append('"');

        foreach (var c in text)
        {
            switch (c)
            {
                case '"': builder.Append("\\\""); break;
                case '\\': builder.Append("\\\\"); break;
                case '\n': builder.Append("\\n"); break;
                case '\r': builder.Append("\\r"); break;
                case '\t': builder.Append("\\t"); break;
                case < ' ': builder.Append("\\u").Append(((int)c).ToString("x4", CultureInfo.InvariantCulture)); break;
                default: builder.Append(c); break;
            }
        }

        return builder.Append('"').ToString();
    }

    private static void Comment(StringBuilder output, string? summary, string indent)
    {
        if (string.IsNullOrEmpty(summary)) return;

        var text = summary.Replace("*/", "*\\/", StringComparison.Ordinal);

        if (indent.Length + text.Length + 7 <= CommentWidth)
        {
            output.Append(indent).Append("/** ").Append(text).Append(" */\n");
            return;
        }

        output.Append(indent).Append("/**\n");

        var line = new StringBuilder();
        foreach (var word in text.Split(' '))
        {
            if (line.Length > 0 && indent.Length + 3 + line.Length + 1 + word.Length > CommentWidth)
            {
                output.Append(indent).Append(" * ").Append(line).Append('\n');
                line.Clear();
            }

            if (line.Length > 0) line.Append(' ');
            line.Append(word);
        }

        if (line.Length > 0) output.Append(indent).Append(" * ").Append(line).Append('\n');
        output.Append(indent).Append(" */\n");
    }
}
