<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Mailcoded.Integration</RootNamespace>
    <IsPackable>false</IsPackable>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <IsAotCompatible>false</IsAotCompatible>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Testcontainers" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Mailcoded.Core/Mailcoded.Core.csproj" />
    <ProjectReference Include="../../src/Mailcoded.Daemon/Mailcoded.Daemon.csproj" />
  </ItemGroup>
</Project>
