// GENERATED by tools/Mailcoded.Protocol.TypeScript from Mailcoded.Protocol. Do not edit.
// Regenerate with `npm run gen:types` (or scripts/gen-types.sh). The drift test in
// tests/Mailcoded.Core.Tests/Protocol/TypeScriptTypesTests.cs fails while this file is stale.
/* eslint-disable */

export const PROTOCOL_VERSION = 1;

/** `account.add` — registers an account. The credential must already be in the secret store. */
export interface AccountAddParams {
  email: string;
  displayName?: string;
  /** `imap|graph|jmap|gmail`. */
  provider?: string;
  imap: ImapConfigDto;
  smtp?: SmtpConfigDto;
  auth?: AuthDto;
  /** Handle previously registered through `secret.set`. Never the credential itself. */
  secretRef: string;
}

export interface AccountAddResult {
  accountId: number;
}

/**
 * An account without any credential. AccountDto.SecretRef is an opaque handle, never a secret.
 */
export interface AccountDto {
  id: number;
  email: string;
  displayName?: string;
  /** `imap|graph|jmap|gmail`. */
  provider: string;
  /** `password|oauth2`. */
  auth: string;
  imap?: ImapConfigDto;
  smtp?: SmtpConfigDto;
  /**
   * Handle into the OS keyring or encrypted-file vault. Resolving it is the daemon's job alone.
   */
  secretRef?: string;
  /** Latched server quirk names, for diagnostics. */
  quirks: readonly string[];
}

export interface AccountHealthDto {
  accountId: number;
  email: string;
  /** `connected|connecting|disconnected|error`. */
  connection: string;
  /** `ok|auth-required|unknown`. */
  auth: string;
  watching: boolean;
  consecutiveFailures: number;
  /** Last failure, redacted. Never a credential, never mail content. */
  lastError?: string;
  /** ISO 8601 UTC. */
  lastSyncUtc?: string;
  outboxQueued: number;
  outboxFailed: number;
}

/** `account.list`. */
export interface AccountListParams {}

export interface AccountListResult {
  accounts: readonly AccountDto[];
}

/** `account.test` — prove the stored settings and credential still work. */
export interface AccountTestParams {
  accountId: number;
}

export interface AccountTestResult {
  /** `ok|auth|network|unsupported` for each leg. */
  imap: string;
  smtp: string;
  folders: number;
  /** Short and redacted; never a credential. */
  imapDetail?: string;
  smtpDetail?: string;
}

/** One MIME attachment, described but not transferred. Content comes from `attachment.get`. */
export interface AttachmentDto {
  /** Stable within one message; the index `attachment.get` takes. */
  index: number;
  /** Already sanitized for use as a save-as name; still never pass it to a shell. */
  filename?: string;
  mime: string;
  size: number;
  isInline: boolean;
  contentId?: string;
}

/** `attachment.get` — one attachment's bytes, base64 encoded. */
export interface AttachmentGetParams {
  messageId: number;
  index: number;
}

export interface AttachmentGetResult {
  filename: string;
  mime: string;
  /** Decoded attachment bytes, base64 encoded. Size is the decoded length. */
  base64: string;
  size: number;
}

export interface AuthDto {
  /** `password|oauth2`. */
  kind?: string;
}

/**
 * What the daemon can do in this session. Absent capabilities are absent features, not toggles.
 */
export interface CapabilitiesDto {
  methods: readonly string[];
  notifications: readonly string[];
  /** Provider kinds this build can connect to. */
  providers: readonly string[];
  search: boolean;
  threading: boolean;
  attachments: boolean;
  watch: boolean;
  /** False unless every send gate is open; a false here means `send` will return `1006`. */
  send: boolean;
  /** Read-only, row-capped SQL, off unless MAILCODED_ENABLE_SQL=1. */
  rawSql: boolean;
  /** True when `message.get` may return `bodyHtml`; agent surfaces get plaintext only. */
  htmlBodies: boolean;
  maxSearchLimit: number;
  /** Which secret backend is active, e.g. `libsecret`. A backend name, never a secret. */
  secretBackend?: string;
}

/**
 * A message a client wants sent. Plaintext body only — HTML compose and attachment upload are
 * out of scope for v0.1. Addresses are validated into `EmailAddress` before anything is built.
 */
export interface DraftDto {
  /** Defaults to the account's own address when omitted. */
  from?: string;
  to?: readonly string[];
  cc?: readonly string[];
  bcc?: readonly string[];
  subject: string;
  bodyText: string;
  /** Message-ID being replied to, without angle brackets. */
  inReplyTo?: string;
  references?: readonly string[];
  /**
   * Local id of the message being replied to; the daemon derives References from it when set.
   */
  replyToMessageId?: number;
}

/**
 * The message summary every list, thread, search hit, and notification renders. Ids are local
 * row ids; EnvelopeDto.Date is an ISO 8601 UTC string so no client has to guess a timezone.
 * EnvelopeDto.Flags are server IMAP flags, EnvelopeDto.Tags are local Tags — the two
 * vocabularies are distinct and never merged.
 */
export interface EnvelopeDto {
  id: number;
  accountId: number;
  folderId: number;
  threadKey?: string;
  /** RFC 5322 Message-ID without angle brackets, or null when the message had none. */
  messageId?: string;
  subject?: string;
  /** Display form of the From header, already decoded. Untrusted attacker input. */
  from?: string;
  to?: string;
  cc?: string;
  /** ISO 8601 UTC, e.g. `2026-08-30T12:34:56.000Z`. */
  date: string;
  /** Server flags: `unread|flagged|answered|draft|deleted|recent`. */
  flags: readonly string[];
  /** Local notmuch-style tags. */
  tags: readonly string[];
  hasAttachments: boolean;
  size: number;
  /**
   * True once the body has been fetched and indexed; false means `message.get` will hit the
   * network.
   */
  bodyFetched: boolean;
  /** Search-result excerpt, present only on hits from `search` when snippets were requested. */
  snippet?: string;
}

/** A folder as the client renders it. FolderDto.Name uses '/' as the hierarchy delimiter. */
export interface FolderDto {
  id: number;
  accountId: number;
  name: string;
  /** `inbox|sent|drafts|trash|archive|junk|all`, or null when the folder has no special use. */
  role?: string;
  unread: number;
  total: number;
}

/** `folder.list`. */
export interface FolderListParams {
  accountId: number;
}

export interface FolderListResult {
  folders: readonly FolderDto[];
}

/**
 * Per-folder sync position. MODSEQ is a string because it exceeds JavaScript's safe integer
 * range.
 */
export interface FolderSyncStatDto {
  folderId: number;
  accountId: number;
  name: string;
  /** Decimal MODSEQ as a string; "0" means the server never reported one. */
  highestModSeq: string;
  uidNext?: number;
  unread: number;
  total: number;
  /** ISO 8601 UTC of the last successful sync, or null if never synced. */
  lastSyncUtc?: string;
}

/** `notify.folder.updated` — counts or state changed; refresh the badge. */
export interface FolderUpdatedNotification {
  accountId: number;
  folder: FolderDto;
}

/** Liveness and per-account connection/auth state (RELIABILITY §14.6). */
export interface HealthDto {
  /** `ok|degraded|error`. */
  status: string;
  storeOk: boolean;
  /** Result of the last `PRAGMA quick_check`, when one has run. */
  storeDetail?: string;
  accounts: readonly AccountHealthDto[];
  /** Stable warning slugs, e.g. `degraded-sync`, `wal-growth`. Safe to log. */
  warnings: readonly string[];
}

/** `health` — per-account connection and auth state. */
export interface HealthParams {}

export interface HealthResult {
  health: HealthDto;
}

export interface ImapConfigDto {
  host: string;
  port?: number;
  /** `none|sslOnConnect|startTls|startTlsWhenAvailable`. */
  security?: string;
  username?: string;
  /** Folders to hold an IDLE connection on. Empty means INBOX only. */
  watchFolders?: readonly string[];
}

/** `initialize` — the first call on every connection. */
export interface InitializeParams {
  clientName: string;
  clientVersion: string;
  protocolVersion?: number;
  /** Audit origin for `sync_log.interface`: `cli|mcp|rpc|internal`. */
  interface?: string;
  /** Best-effort agent host name for `sync_log.agent_host`. */
  agentHost?: string;
}

export interface InitializeResult {
  daemonVersion: string;
  protocolVersion: number;
  capabilities: CapabilitiesDto;
}

/** A JSON-RPC 2.0 error object. Neither field ever carries a secret or mail content. */
export interface JsonRpcError {
  code: number;
  /** Short, stable, human-readable. Never interpolate a header, body, or credential into it. */
  message: string;
  data?: RpcErrorData;
}

/** A JSON-RPC 2.0 notification: no id, no response. */
export interface JsonRpcNotification {
  jsonrpc?: string;
  method: string;
  params?: unknown;
}

/**
 * A JSON-RPC 2.0 request. JsonRpcRequest.Id is absent on a notification and may be a number or
 * a string, so it stays an untyped JsonElement and is echoed back verbatim.
 */
export interface JsonRpcRequest {
  jsonrpc?: string;
  id?: unknown;
  method: string;
  /** Left undecoded so the dispatcher can pick the source-generated type for the method. */
  params?: unknown;
}

/**
 * A JSON-RPC 2.0 response. Exactly one of JsonRpcResponse.Result and JsonRpcResponse.Error is
 * written; hosts that care about allocation should stream the result with `Utf8JsonWriter`
 * instead.
 */
export interface JsonRpcResponse {
  jsonrpc: string;
  id?: unknown;
  result?: unknown;
  error?: JsonRpcError;
}

/** `notify.mail.added` — new messages landed in a watched folder. */
export interface MailAddedNotification {
  accountId: number;
  folderId: number;
  folderName: string;
  /**
   * How many arrived; may exceed MailAddedNotification.Messages when the batch was coalesced.
   */
  count: number;
  /** Newest arrivals, capped so an IDLE storm cannot flood the client (edge case 27). */
  messages: readonly EnvelopeDto[];
}

/** `message.get` — envelope plus body. Fetches from the server when the body is not local. */
export interface MessageGetParams {
  messageId: number;
  /** `text|html|raw`. */
  format?: string;
  fetchIfMissing?: boolean;
}

export interface MessageGetResult {
  envelope: EnvelopeDto;
  /** Plaintext extraction, present for format `text` and `html`. */
  bodyText?: string;
  /**
   * RAW, UNSANITIZED attacker-controlled HTML — the client sanitizes before rendering, never
   * the daemon.
   */
  bodyHtml?: string;
  /** Base64 RFC822 bytes, present only for format `raw`. */
  raw?: string;
  attachments: readonly AttachmentDto[];
  bodyFetched: boolean;
  /** Stable parser warning slugs, e.g. `missing-date`. Never echo mail content. */
  parseWarnings: readonly string[];
}

/** `message.move` — move to another folder. There is no delete or expunge method. */
export interface MessageMoveParams {
  messageId: number;
  toFolderId: number;
}

export interface MessageMoveResult {}

/** One outbox row as a client renders it. No raw bytes and no body. */
export interface OutboxEntryDto {
  id: number;
  accountId: number;
  state: string;
  messageId: string;
  to: readonly string[];
  attempts: number;
  permanentlyFailed: boolean;
  smtpResponse?: string;
  /** ISO 8601 UTC. */
  createdUtc: string;
  nextAttemptUtc?: string;
  /** False until a confirm token was consumed; such a row is a draft, never sent. */
  confirmed: boolean;
}

/** `outbox.list` — what is queued, sending, sent or stuck. Carries no message body. */
export interface OutboxListParams {
  accountId?: number;
  /** `queued|sending|sent|failed`, or null for everything. */
  state?: string;
  limit?: number;
}

export interface OutboxListResult {
  entries: readonly OutboxEntryDto[];
}

/**
 * `provider.detect` — settings and credential guidance for an address, so a client can pre-fill
 * onboarding. A table lookup: no network, nothing stored.
 */
export interface ProviderDetectParams {
  email: string;
}

export interface ProviderDetectResult {
  preset: ProviderPresetDto;
}

/**
 * What a client shows on its onboarding screen. ProviderPresetDto.Imap and
 * ProviderPresetDto.Smtp are shaped so they can be handed to `account.add` once the human has
 * confirmed them.
 */
export interface ProviderPresetDto {
  displayName: string;
  imap: ImapConfigDto;
  smtp: SmtpConfigDto;
  /** `password|appPassword|oauthOnly`. */
  credential: string;
  /**
   * Where the human creates the credential. Open it with the platform's external opener; never
   * render it as HTML.
   */
  credentialUrl?: string;
  /** One line the human should read before typing a credential. */
  advice?: string;
  /**
   * True when the hosts were guessed from the domain rather than known, so a client must show
   * them as editable.
   */
  isGuess: boolean;
  /**
   * Set when the provider usually refuses an ordinary password. A warning to display, not a
   * reason to block the attempt.
   */
  discouraged?: string;
}

/**
 * Machine-readable detail attached to an error so a client can branch without parsing prose.
 */
export interface RpcErrorData {
  /** Adapter failure category: `network|protocol|auth|busy|full|notFound|unsupported`. */
  category?: string;
  /** Extra context that is safe to display. Never mail content, never a credential. */
  detail?: string;
  /** How long to wait before retrying, when the daemon can estimate it. */
  retryAfterMs?: number;
  /** True when no retry will help until the user re-authenticates or changes settings. */
  requiresUserAction?: boolean;
  accountId?: number;
  folderId?: number;
}

/** `search` — FTS5 query with keyset paging. Always pass a limit. */
export interface SearchParams {
  /** Query in the `from:/to:/subject:/tag:/is:/before:/after:` syntax. Untrusted text. */
  query: string;
  limit?: number;
  /** Opaque keyset cursor from a previous SearchResult.NextCursor. */
  cursor?: string;
  accountId?: number;
  folderId?: number;
  /** `relevance|date`. Defaults to relevance for text queries. */
  order?: string;
  includeSnippet?: boolean;
}

export interface SearchResult {
  hits: readonly EnvelopeDto[];
  nextCursor?: string;
  /**
   * True when results were cut short; follow SearchResult.NextCursor rather than assuming
   * completeness.
   */
  truncated: boolean;
}

/**
 * `secret.set` — the only DTO that ever holds a credential, and only inbound. The value goes
 * straight to the secret store; it is never logged, echoed, or persisted elsewhere.
 */
export interface SecretSetParams {
  /** The handle an account's `secretRef` will point at. */
  ref: string;
  /** The credential. Redacted from ToString so it cannot leak through a log line. */
  value: string;
}

export interface SecretSetResult {}

/**
 * `send` — phase two. Rejected with 1003 without a valid, unexpired, unconsumed token, and with
 * 1006 when a Core safety gate is closed. Every attempt writes to `sync_log`.
 */
export interface SendParams {
  accountId: number;
  draftId: number;
  confirmToken: string;
}

/** What the human confirms before a send. The one place recipients are shown in full. */
export interface SendPreviewDto {
  from: string;
  to: readonly string[];
  cc: readonly string[];
  bcc: readonly string[];
  subject: string;
  /** Plaintext excerpt of the body, truncated for display. */
  bodyPreview: string;
  bodyTruncated: boolean;
  sizeBytes: number;
  /** Pre-assigned at outbox creation and immutable; the idempotency key for the send. */
  messageId: string;
  requiresSmtpUtf8: boolean;
  /** Stable slugs, e.g. `smtputf8-unsupported`, `exceeds-server-size-limit`. */
  warnings: readonly string[];
}

/**
 * `send.preview` — phase one of the two-phase send. Builds the message, stores it in the outbox
 * as a draft, and returns the one-time token phase two requires.
 */
export interface SendPreviewParams {
  accountId: number;
  draft: DraftDto;
}

export interface SendPreviewResult {
  /** Outbox row id; `send` takes this as `draftId`. */
  draftId: number;
  preview: SendPreviewDto;
  /** Single-use, bound to this draft. Not a secret in the keyring sense, but never log it. */
  confirmToken: string;
  /** ISO 8601 UTC after which the token is rejected with error 1003. */
  confirmTokenExpiresUtc?: string;
}

export interface SendResult {
  /** The pre-assigned RFC 5322 Message-ID, without angle brackets. */
  messageId: string;
  /** Outbox state after the attempt: `queued|sending|sent|failed`. */
  state: string;
  outboxId?: number;
  /** Sanitized, length-capped SMTP reply line for the audit record. */
  smtpResponse?: string;
}

/** `shutdown` — drain and exit. */
export interface ShutdownParams {}

export interface ShutdownResult {}

export interface SmtpConfigDto {
  host: string;
  port?: number;
  /** `none|sslOnConnect|startTls|startTlsWhenAvailable`. */
  security?: string;
  username?: string;
}

/** Daemon metrics (RELIABILITY §14.6). Nothing here identifies a message or a person. */
export interface StatsDto {
  daemonVersion: string;
  protocolVersion: number;
  uptimeMs: number;
  workingSetBytes: number;
  gcHeapBytes: number;
  gcCommittedBytes: number;
  gcTotalAllocatedBytes: number;
  gen0Collections: number;
  gen1Collections: number;
  gen2Collections: number;
  threadCount: number;
  handleCount: number;
  /** IMAP connections currently open across all accounts. */
  openConnections: number;
  schemaVersion: number;
  databaseSizeBytes: number;
  walSizeBytes: number;
  blobDirectorySizeBytes: number;
  tableCounts: Readonly<Record<string, number>>;
  folders: readonly FolderSyncStatDto[];
}

/** `stats` — daemon metrics. */
export interface StatsParams {}

export interface StatsResult {
  stats: StatsDto;
}

/** `notify.sync.error` — a background sync or watch failed. Carries no mail content. */
export interface SyncErrorNotification {
  accountId: number;
  folderId?: number;
  /** The same stable numeric code the equivalent request error would carry. */
  code: number;
  /** Short and redacted: never a credential, never a header or body. */
  message: string;
  /** `network|protocol|auth|busy|full|notFound|unsupported`. */
  category?: string;
  /**
   * True when backoff alone will not recover; the user must re-authenticate or fix settings.
   */
  requiresUserAction: boolean;
  retryAfterMs?: number;
  /** ISO 8601 UTC. */
  atUtc: string;
}

/** `sync` — one folder when SyncParams.FolderId is set, otherwise the whole account. */
export interface SyncParams {
  accountId: number;
  folderId?: number;
}

export interface SyncResult {
  added: number;
  updated: number;
  expunged: number;
  durationMs: number;
}

/**
 * `tags.set` — apply a tag delta; the server flag projection follows in the same transaction.
 */
export interface TagsSetParams {
  messageId: number;
  add?: readonly string[];
  remove?: readonly string[];
}

export interface TagsSetResult {
  /** The message's complete tag set after the delta, sorted ordinal. */
  tags: readonly string[];
}

/** `thread.get` — every message sharing a thread key, oldest first. */
export interface ThreadGetParams {
  threadKey: string;
  limit?: number;
}

export interface ThreadGetResult {
  messages: readonly EnvelopeDto[];
  truncated: boolean;
}

/** `watch.subscribe` — start delivering notifications for an account. */
export interface WatchSubscribeParams {
  accountId: number;
  /** Folders to hold IDLE on. Empty means the account's configured watch set. */
  folderIds?: readonly number[];
}

export interface WatchSubscribeResult {}

/** Wire values for `Providers.AuthKind`. */
export const AuthKinds = {
  Password: "password",
  OAuth2: "oauth2",
} as const;
export type AuthKindsValue = (typeof AuthKinds)[keyof typeof AuthKinds];

/** Wire values for `Providers.CredentialStyle`: what a provider accepts as a credential. */
export const CredentialStyles = {
  Password: "password",
  AppPassword: "appPassword",
  OAuthOnly: "oauthOnly",
} as const;
export type CredentialStylesValue = (typeof CredentialStyles)[keyof typeof CredentialStyles];

/** Wire vocabulary for server IMAP flags. Tags are a separate vocabulary. */
export const FlagNames = {
  Unread: "unread",
  Flagged: "flagged",
  Answered: "answered",
  Draft: "draft",
  Deleted: "deleted",
  Recent: "recent",
} as const;
export type FlagNamesValue = (typeof FlagNames)[keyof typeof FlagNames];

/** Values of HealthDto.Status and AccountHealthDto.Connection. */
export const HealthStates = {
  Ok: "ok",
  Degraded: "degraded",
  Error: "error",
  Connected: "connected",
  Connecting: "connecting",
  Disconnected: "disconnected",
  AuthOk: "ok",
  AuthRequired: "auth-required",
  AuthUnknown: "unknown",
} as const;
export type HealthStatesValue = (typeof HealthStates)[keyof typeof HealthStates];

/** ISO 8601, always UTC, always Z-suffixed, so no client infers an offset. */
export const IsoTime = {
  Format: "yyyy-MM-dd'T'HH:mm:ss.fff'Z'",
} as const;
export type IsoTimeValue = (typeof IsoTime)[keyof typeof IsoTime];

/** Accepted values of MessageGetParams.Format. */
export const MessageFormats = {
  Text: "text",
  Html: "html",
  Raw: "raw",
} as const;
export type MessageFormatsValue = (typeof MessageFormats)[keyof typeof MessageFormats];

/** Values of SendResult.State, mirroring `Domain.Outbox.OutboxState`. */
export const OutboxStates = {
  Queued: "queued",
  Sending: "sending",
  Sent: "sent",
  Failed: "failed",
} as const;
export type OutboxStatesValue = (typeof OutboxStates)[keyof typeof OutboxStates];

/** Wire-level constants shared by every client of the JSON-RPC surface (SPEC §5.6). */
export const ProtocolConstants = {
  /** The negotiated protocol version. Bump only on a breaking DTO change. */
  Version: 1,
  JsonRpcVersion: "2.0",
} as const;

/** Wire values for `Providers.ProviderKind`, mirroring `ProviderKindExtensions`. */
export const ProviderKinds = {
  Imap: "imap",
  Graph: "graph",
  Jmap: "jmap",
  Gmail: "gmail",
} as const;
export type ProviderKindsValue = (typeof ProviderKinds)[keyof typeof ProviderKinds];

/** Method names, exactly as they appear on the wire. */
export const RpcMethods = {
  Initialize: "initialize",
  SecretSet: "secret.set",
  AccountAdd: "account.add",
  AccountList: "account.list",
  FolderList: "folder.list",
  Sync: "sync",
  Search: "search",
  ThreadGet: "thread.get",
  MessageGet: "message.get",
  AttachmentGet: "attachment.get",
  TagsSet: "tags.set",
  MessageMove: "message.move",
  SendPreview: "send.preview",
  Send: "send",
  WatchSubscribe: "watch.subscribe",
  Stats: "stats",
  Health: "health",
  AccountTest: "account.test",
  OutboxList: "outbox.list",
  ProviderDetect: "provider.detect",
  Shutdown: "shutdown",
} as const;
export type RpcMethodsValue = (typeof RpcMethods)[keyof typeof RpcMethods];

/** Server-to-client notification method names. Notifications never carry an id. */
export const RpcNotifications = {
  MailAdded: "notify.mail.added",
  FolderUpdated: "notify.folder.updated",
  SyncError: "notify.sync.error",
} as const;
export type RpcNotificationsValue = (typeof RpcNotifications)[keyof typeof RpcNotifications];

/** Accepted values of SearchParams.Order. */
export const SearchOrders = {
  Relevance: "relevance",
  Date: "date",
} as const;
export type SearchOrdersValue = (typeof SearchOrders)[keyof typeof SearchOrders];

/** Wire values for `Providers.SecureSocket`. The daemon maps these to the enum. */
export const SecurityModes = {
  None: "none",
  SslOnConnect: "sslOnConnect",
  StartTls: "startTls",
  StartTlsWhenAvailable: "startTlsWhenAvailable",
} as const;
export type SecurityModesValue = (typeof SecurityModes)[keyof typeof SecurityModes];

/**
 * Stable numeric JSON-RPC error codes (SPEC §5.6). Values are a wire contract: never renumber
 * one, never reuse a retired number. Document every addition in `docs/rpc.md`.
 */
export const RpcErrorCode = {
  /** Malformed JSON was received. Standard JSON-RPC 2.0 code. */
  ParseError: -32700,
  /** The payload was valid JSON but not a valid JSON-RPC request object. */
  InvalidRequest: -32600,
  /** No method with that name exists on this protocol version. */
  MethodNotFound: -32601,
  /** Params were missing, of the wrong type, or failed validation. */
  InvalidParams: -32602,
  /** An unhandled failure inside the daemon. The message never carries mail content. */
  InternalError: -32603,
  /**
   * Authentication to the mail server failed or the stored credential is gone; the user must
   * act.
   */
  Auth: 1000,
  /** A transient network or TLS failure. Safe to retry after backoff. */
  Network: 1001,
  /** The requested account, folder, message, attachment, thread, or draft does not exist. */
  NotFound: 1002,
  /** A send was attempted without a valid one-time confirm token, or the token expired. */
  ConfirmRequired: 1003,
  /**
   * The local store failed an integrity check; re-sync from the server is the recovery path.
   */
  StoreCorrupt: 1004,
  /**
   * A rate limit or busy-writer backpressure rejected the call. Retry after the hinted delay.
   */
  RateLimited: 1005,
  /**
   * A Core safety gate refused the call: send disabled, recipient not allowlisted, raw SQL off.
   */
  Forbidden: 1006,
  /**
   * The disk or the database is full (SQLITE_FULL); sync is paused rather than risking
   * corruption.
   */
  StoreFull: 1007,
  /**
   * The server or provider lacks a capability the call requires, e.g. SMTPUTF8 for an EAI
   * recipient.
   */
  Unsupported: 1008,
} as const;
export type RpcErrorCode = (typeof RpcErrorCode)[keyof typeof RpcErrorCode];

export interface RpcMethodMap {
  "initialize": { params: InitializeParams; result: InitializeResult };
  "secret.set": { params: SecretSetParams; result: SecretSetResult };
  "account.add": { params: AccountAddParams; result: AccountAddResult };
  "account.list": { params: AccountListParams; result: AccountListResult };
  "folder.list": { params: FolderListParams; result: FolderListResult };
  "sync": { params: SyncParams; result: SyncResult };
  "search": { params: SearchParams; result: SearchResult };
  "thread.get": { params: ThreadGetParams; result: ThreadGetResult };
  "message.get": { params: MessageGetParams; result: MessageGetResult };
  "attachment.get": { params: AttachmentGetParams; result: AttachmentGetResult };
  "tags.set": { params: TagsSetParams; result: TagsSetResult };
  "message.move": { params: MessageMoveParams; result: MessageMoveResult };
  "send.preview": { params: SendPreviewParams; result: SendPreviewResult };
  "send": { params: SendParams; result: SendResult };
  "watch.subscribe": { params: WatchSubscribeParams; result: WatchSubscribeResult };
  "stats": { params: StatsParams; result: StatsResult };
  "health": { params: HealthParams; result: HealthResult };
  "account.test": { params: AccountTestParams; result: AccountTestResult };
  "outbox.list": { params: OutboxListParams; result: OutboxListResult };
  "provider.detect": { params: ProviderDetectParams; result: ProviderDetectResult };
  "shutdown": { params: ShutdownParams; result: ShutdownResult };
}
export type RpcMethodName = keyof RpcMethodMap;

export interface RpcNotificationMap {
  "notify.mail.added": MailAddedNotification;
  "notify.folder.updated": FolderUpdatedNotification;
  "notify.sync.error": SyncErrorNotification;
}
export type RpcNotificationName = keyof RpcNotificationMap;
