<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Mailcoded.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MailKit" />
    <PackageReference Include="MimeKit" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Store/Migrations/*.sql" />
  </ItemGroup>
</Project>
